name: Build, Sign, and Release APK

on:
  push:
    branches:
      - master

jobs:
  build-sign-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Decode Keystore Secret
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" > my-release-key.keystore.base64
          base64 -d -i my-release-key.keystore.base64 > my-release-key.keystore
        shell: bash

      - name: Build and Sign APK
        run: |
          ./gradlew assembleRelease
          cp app/build/outputs/apk/release/app-release.apk $GITHUB_WORKSPACE/JetTipApp.apk
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

      - name: Wait for 10 seconds
        run: sleep 10

      - name: Create ZIP Archive
        run: |
          zip -r "Source code.zip" JetTipApp.apk
        working-directory: ${{ github.workspace }}

      - name: Create TAR.GZ Archive
        run: |
          tar -czvf "Source code.tar.gz" JetTipApp.apk
        working-directory: ${{ github.workspace }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            Source code.zip
            Source code.tar.gz
          tag_name: v1.0
          release_name: JetTipApp 1.0  # Replace with your desired release name
          body: |
            - A basic tipping app calculator created with JetPack Compose

      - name: Upload APK as Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: $GITHUB_WORKSPACE/JetTipApp.apk
          asset_name: JetTipApp.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Remove Keystore Files
        run: |
          rm -f my-release-key.keystore my-release-key.keystore.base64
        shell: bash
